name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build-debian-testing:
    name: Debian Testing
    runs-on: ubuntu-latest
    container: debian:testing

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install deps
        run: |
          apt-get update
          apt-get dist-upgrade --purge -y
          apt-get -y install build-essential cmake doxygen graphviz libdbus-1-dev libglib2.0-dev libgtk-3-dev libmtdev-dev libudev-dev libwayland-dev libxcb-composite0-dev libxcb-damage0-dev libxcb-xfixes0-dev libxext-dev libxkbcommon-dev pkg-config qml-module-qtquick2 qtbase5-dev qtbase5-private-dev qtdeclarative5-dev qtwayland5-dev-tools qtwayland5-private-dev

      - name: Build
        run: |
          cmake -DCMAKE_BUILD_TYPE=debug -DCMAKE_INSTALL_PREFIX=/usr .
          make -j8

      - name: Test
        run: |
          make ARGS+="-j8 --output-on-failure" test
